'use strict';
window.STORIA52_V2_WORLDS={
  "museum": {
    "roles": ["Una giovane restauratrice","Un custode al suo ultimo turno","Una studentessa di storia","Un fotografo incaricato del catalogo","Una guida che conosce ogni sala","Una nuova archivista"],
    "details": ["che si fida solo del custode","che deve aiutare un familiare","che ha promesso di non coinvolgere nessuno","che dipende dall’aiuto di una collega","che vuole rimediare a un vecchio errore","che non può spiegare perché è lì"],
    "places": ["Nel deposito del museo","Nell’archivio sotterraneo","Nella sala chiusa per restauro","Nel corridoio riservato al personale","Nel laboratorio dietro la galleria","Nella biblioteca del museo"],
    "events": ["trova una fotografia recente dentro un registro antico","nota che una teca è stata spostata","scopre un nome cancellato dall’inventario","sente squillare un telefono in una sala vuota","trova una chiave con il numero di una stanza inesistente","vede una luce accesa in un piano dichiarato chiuso"],
    "actions": ["Confronta il registro con le fotografie","Raggiunge il custode prima che finisca il turno","Apre la cartella collegata all’oggetto mancante","Porta la prova alla persona che può confermarla","Recupera il documento prima della chiusura","Chiede aiuto alla collega che aveva evitato"],
    "methods": ["usando l’indizio appena trovato","senza avvisare il direttore","prima dell’arrivo dei visitatori","con pochi minuti a disposizione","mettendo da parte il proprio piano","accettando di perdere qualcosa di importante"],
    "obstacles": ["Il custode cambia versione","L’archivio viene chiuso in anticipo","La fotografia scompare dal registro","La collega rifiuta di aiutarla","L’oggetto viene trasferito altrove","Il direttore anticipa l’ispezione"],
    "costs": ["resta una sola occasione per verificare la prova","deve scegliere tra il documento e la persona che sta aiutando","il suo piano non può più continuare come previsto","qualcuno vicino a lei rischia di pagarne le conseguenze","la verità potrebbe arrivare troppo tardi","per continuare deve rinunciare alla soluzione più facile"]
  },
  "station": {
    "roles": ["Una pendolare che conosce ogni orario","Un padre arrivato in ritardo","Una ragazza al suo primo viaggio da sola","Un capotreno vicino alla pensione","Un corriere con una consegna urgente","Una musicista diretta a un’audizione"],
    "details": ["che aspetta l’aiuto di uno sconosciuto","che deve raggiungere una persona importante","che ha promesso di tornare prima dell’alba","che non può perdere un’altra occasione","che nasconde il vero motivo del viaggio","che deve scegliere chi accompagnare"],
    "places": ["Sul binario quasi vuoto","Nella sala d’attesa della stazione","Davanti all’ultimo treno della notte","Nel sottopassaggio chiuso a metà","All’ufficio informazioni senza personale","Nel bar della stazione durante la chiusura"],
    "events": ["trova un biglietto intestato a una persona assente","nota una valigia identica alla propria","riceve un messaggio inviato dal treno già partito","vede cambiare all’improvviso il binario","trova una fotografia nascosta nella custodia del biglietto","sente il proprio nome nell’annuncio degli altoparlanti"],
    "actions": ["Raggiunge il nuovo binario prima della partenza","Consegna il biglietto alla persona indicata","Chiama l’unico contatto scritto sul retro","Segue la valigia fino all’ufficio informazioni","Convince il capotreno ad aspettare","Rinuncia al proprio posto per aiutare qualcuno"],
    "methods": ["usando il messaggio appena ricevuto","senza poter spiegare tutto","prima dell’ultimo annuncio","con l’aiuto di un solo passeggero","lasciando indietro il proprio bagaglio","cambiando il piano all’ultimo momento"],
    "obstacles": ["L’ultimo treno parte in anticipo","Il biglietto risulta intestato a un’altra persona","Il capotreno riceve un ordine contrario","La persona attesa non si presenta","Il tabellone cambia di nuovo destinazione","Il telefono si spegne prima della risposta"],
    "costs": ["non avrà una seconda partenza","deve scegliere chi lasciare sul binario","la persona che cerca potrebbe allontanarsi per sempre","per continuare deve abbandonare il proprio viaggio","l’occasione resta aperta solo per pochi minuti","la scelta sbagliata renderà inutile tutto il piano"]
  },
  "hospital": {
    "roles": ["Una giovane infermiera","Un padre in attesa di notizie","Una specializzanda al primo turno","Un autista che accompagna un paziente","Una volontaria del reparto","Un tecnico della manutenzione"],
    "details": ["che deve aiutare una persona sola","che dipende dall’autorizzazione di un medico","che vuole correggere un errore","che non può spiegare tutta la situazione","che ha promesso di restare fino alla fine","che deve scegliere chi avvisare per primo"],
    "places": ["Nella sala d’attesa quasi vuota","Nel corridoio tra due reparti","Davanti all’archivio delle cartelle","Nella stanza riservata ai familiari","All’ingresso durante il cambio turno","Nel piccolo ufficio del reparto"],
    "events": ["trova una cartella con due nomi diversi","riceve un messaggio destinato a un’altra famiglia","nota che un appuntamento è stato cancellato","scopre una firma mancante nel documento","vede arrivare una persona che nessuno aspettava","trova una fotografia dentro una cartella clinica"],
    "actions": ["Confronta le due cartelle","Raggiunge il medico prima del cambio turno","Avvisa la famiglia indicata nel messaggio","Recupera l’autorizzazione mancante","Accompagna la persona nel reparto corretto","Rinuncia al proprio appuntamento per restare con qualcuno"],
    "methods": ["senza creare altro caos","usando il documento appena trovato","prima che il turno finisca","con l’aiuto di una sola collega","mettendo da parte il proprio problema","accettando una conseguenza personale"],
    "obstacles": ["Il medico lascia il reparto prima del previsto","Le due cartelle vengono separate","La famiglia riceve una versione diversa","L’autorizzazione viene rimandata","La persona che aspettava cambia idea","Il reparto viene trasferito temporaneamente"],
    "costs": ["resta pochissimo tempo per chiarire l’errore","deve scegliere chi aiutare per primo","il rapporto con una persona importante potrebbe spezzarsi","per continuare deve rinunciare al proprio piano","la verità potrebbe arrivare quando non serve più","qualcuno resterà senza la risposta che aspettava"]
  },
  "workshop": {
    "roles": ["Una giovane meccanica","Un apprendista al primo giorno","Il proprietario di una piccola officina","Una corriera con una consegna urgente","Un tecnico arrivato da fuori città","Una cliente che conosce il vecchio progetto"],
    "details": ["che dipende dall’aiuto del suo ex collega","che deve completare un lavoro importante","che vuole salvare l’attività di famiglia","che non può permettersi un altro errore","che protegge il progetto di una persona","che deve scegliere tra il cliente e la squadra"],
    "places": ["Nell’officina dopo la chiusura","Davanti al banco degli attrezzi","Nel magazzino dei pezzi di ricambio","Accanto al mezzo pronto per la consegna","Nel piccolo ufficio sopra l’officina","Sotto la tettoia durante un temporale"],
    "events": ["trova un pezzo segnato con una data futura","scopre una modifica non registrata nel progetto","riceve una telefonata dal vecchio proprietario","nota che manca l’unico componente necessario","trova una ricevuta collegata a un vecchio errore","vede arrivare un cliente che non doveva sapere del lavoro"],
    "actions": ["Confronta il progetto con il mezzo","Chiama l’ex collega prima della consegna","Recupera il componente da un secondo macchinario","Rifà il lavoro seguendo la modifica trovata","Consegna la ricevuta alla persona coinvolta","Rinuncia al guadagno per completare il lavoro correttamente"],
    "methods": ["usando soltanto i pezzi disponibili","senza avvisare il cliente","prima che arrivi il corriere","con l’aiuto di un solo collega","mettendo a rischio la consegna","accettando di perdere il lavoro già fatto"],
    "obstacles": ["Il cliente anticipa il ritiro","L’ex collega rifiuta di rispondere","Il componente non è compatibile","La modifica crea un secondo problema","La squadra vuole consegnare comunque","Il temporale blocca il trasporto"],
    "costs": ["non ci sarà tempo per un altro tentativo","deve scegliere tra la consegna e la sicurezza","l’attività rischia di perdere il cliente più importante","per continuare deve buttare via ore di lavoro","qualcuno vicino a lei potrebbe assumersi la colpa","il piano deve cambiare prima dell’arrivo del corriere"]
  }
};
